version: '3'
services:
  java:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - .:/workdir
    working_dir: /workdir

    # Fix slow shutdown of web container
    init: true
    # INFO: Following two lines are necessary for the backtrace by pdb
    stdin_open: true
    tty: true
